export interface Job {
    id: string;
    organization_name: string;
    organization_icon: string;
    position: string;
    salary: string;
    type: string;
    city: string;
    created_at: string;
    updated_at: string;
    currency: string;
    gradient: number;
    is_archived: boolean | null;
    organization_icon_formats: { type: string; url: string }[];
    price_from: number;
    price_to: number;
    slug: string;
    workday: string | null;
    date: string;
    time: string;
    location: string;
    title: string;
    cover: string;
    cover_formats: Array<null | { type: string; url: string }>;
    icon: string;
    name: string;
    jobs_count: number;
    events_count: number;
    meetups_count: number;
    telegram_chats: Array<{ title: string; url: string }>;
    telegram_channels: Array<{ title: string; url: string }>;
    websites: Array<{ title: string; url: string }>;
    facebook: Array<{ title: string; url: string }>;
    youtube: Array<{ title: string; url: string }>;
    github: Array<{ title: string; url: string }>;
    devkg: Array<{ label: string; value: string }>;
}
